### ISSUE TITLE
Performance issue on large repos

### ISSUE THREAD

**Issue by vamolessa** [matheuslessarodrigues/verco#4]
It seems that it hangs on startup on large repos (100 million commits).

**Comment by vamolessa** [comment]
It'd be helpful if someone knows of an opensource repository where this happens

**Comment by vamolessa** [comment]
It seems that the culprit is the flag `--graph` that is used by verco.
Testing on git@github.com:torvalds/linux.git, it hangs even from cli doing `git --online --graph -50`

**Comment by Alphare** [comment]
Verco is not the culprit here, it's the same story on large Mercurial repos.

I've had this discussion with another TUI project, but I think after a certain size UI needs to use caching and background update. 
The initial log will be as slow as the underlying VCS, but additional log invocations should be cached and display the (potentially) stale data with a loading icon until it refreshes so that most of the information is still there, because most of the time it's useful.

This is related to #8: allowing the user to switch to another pane while it's loading, etc. will be very useful on larger repositories.

I'm doing what I can to speed up `hg status/diff` but `log` is still pretty slow in general. However, it does seem to scale better than Git's graph, which is surprising to me, since `git log` is much faster on small repos.

**Comment by Alphare** [comment]
The largest open-source hg repo I know of is [Mozilla-Try](https://hg.mozilla.org/try). :)

**Comment by vamolessa** [comment]
I think we can close this since now that actions run in the background and their result is cached making the ui feel responsive.
